version: "3.3"

services:
  database:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_HOST: "%"
    container_name: mysql-db-container
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - 33068:3306
    volumes:
      - db_vol:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer-container
    ports:
      - ${ADMINER_PORT}:8080
    
  liquibase:
    image: webdevops/liquibase:mysql
    container_name: liquibase-container
    links:
      - database
    volumes:
      - .:/liquibase
    environment:
      - LIQUIBASE_CHANGELOG=${LIQUIBASE_CHANGELOG}
      - LIQUIBASE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - LIQUIBASE_USERNAME=${DB_USER}
      - LIQUIBASE_PASSWORD=${DB_PASS}

volumes:
  db_vol: